version: '3.8'

services:
  mongo:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
      args:
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - MONGO_DB=${MONGO_DB}
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env.infra

volumes:
  mongo_data:
